<?xml version="1.0"?>

<robot name="box_robot" xmlns:xacro="http://ros.org/wiki/xacro">

   <!-- Define a number of dimensions using properties -->
   <xacro:property name="torso_offset_x" value="0.0" />
   <xacro:property name="torso_offset_y" value="0.0" />
   <xacro:property name="torso_offset_z" value="0.23" /> <!--base_height/2+torso_height/2 -->

   <!-- Define a number of dimensions of sick sensor using properties -->
   <xacro:property name="sick_radius" value="0.02" />
   <xacro:property name="sick_length" value="0.05" />
   <xacro:property name="sick_offset_x" value="0.30" />
   <xacro:property name="sick_offset_y" value="0.0" />
   <xacro:property name="sick_offset_z" value="0.3" />

   <!-- Include all component files -->
   <xacro:include filename="$(find gpsbot_description)/urdf/gpsbotbase/materials.urdf.xacro" />
   <xacro:include filename="$(find gpsbot_description)/urdf/gpsbotbase/base.urdf.xacro" />
   <!--
<xacro:include filename="$(find gpsbot_description)/urdf/gpsbotbase/torso.urdf.xacro" />
   -->
   <!-- Add the base and wheels -->
   <base name="base" color="DeepSkyBlue"/>
   
   <!-- Attach the torso -->
<!--
   <torso name="torso" parent="base" color="Grey">
      <origin xyz="${torso_offset_x} ${torso_offset_y} ${torso_offset_z}" rpy="0 0 0" />
   </torso>
-->
<!--
 <joint name="laser" type="fixed">
    <origin xyz="0.15 0.00 0.20" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_laser_link" />
  </joint>

  <link name="base_laser_link">
    <visual>
      <geometry>
        <box size="0.00 0.05 0.06" />
      </geometry>
      <material name="Green" />
    </visual>
    <inertial>
      <mass value="0.000001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>
-->

<!--This is for sensor-->
  <link name="front_flag">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
<!--
          <box size="0.08 0.08 0.001" />
-->
	  <cylinder radius="${sick_radius}" length="${sick_length}" />
        </geometry>
        <material name="DarkGrey" />
      </visual>
  </link>

  <joint name="front_point_flag" type="fixed">
    <origin xyz="${sick_offset_x} ${sick_offset_y} ${base_length/2}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="front_flag" />
  </joint>

<!--  <link name="up_flag">-->
<!--      <visual>-->
<!--        <origin xyz="0 0 0" rpy="0 0 0" />-->
<!--        <geometry>-->
<!--<!-->
<!--          <box size="0.08 0.08 0.001" />-->
<!---->
<!--	  <cylinder radius="${base_radius}" length="0.02" />-->
<!--        </geometry>-->
<!--        <material name="Black" />-->
<!--      </visual>-->
<!--  </link>-->

<!--  <joint name="up_point_flag" type="fixed">-->
<!--    <origin xyz="0 0 ${sick_length+base_length/2}" rpy="0 0 0" />-->
<!--    <parent link="base_link"/>-->
<!--    <child link="up_flag" />-->
<!--  </joint>-->

<!--  <link name="laser">-->
<!--      <visual>-->
<!--        <origin xyz="0 0 0" rpy="0 0 0" />-->
<!--        <geometry>-->
<!--<!-->
<!--          <box size="0.08 0.08 0.001" />-->
<!---->
<!--	  <cylinder radius="${base_radius-0.05}" length="0.025" />-->
<!--        </geometry>-->
<!--        <material name="DogerBlue" />-->
<!--      </visual>-->
<!--  </link>-->

<!--  <joint name="base_laser_link" type="fixed">-->
<!--    <origin xyz="0 0 ${sick_length+base_length/2}" rpy="0 0 0" />-->
<!--    <parent link="base_link"/>-->
<!--    <child link="laser" />-->
<!--  </joint>-->

</robot>


